### ISSUE TITLE
add role labels

### ISSUE THREAD

**Issue by johrstrom** [OSC/bc_classroom_jupyter#1]
add labels `osc.edu/role=ondemand` and `osc.edu/role=web` for node selector changes coming.

**Comment by treydock** [comment]
This was deployed to production so can test now if you want:

```
# PRODUCTION
# kubectl get node -o=custom-columns=NAME:.metadata.name,CLUSTER:.metadata.labels.'osc\.edu/role'
NAME             CLUSTER
kubecontroller   <none>
kubeworker01     ondemand
kubeworker02     ondemand
kubeworker03     ondemand
kubeworker04     ondemand
kubeworker05     ondemand
kubeworker06     ondemand
kubeworker07     ondemand
kubeworker08     ondemand

# DEV
# kubectl get node -o=custom-columns=NAME:.metadata.name,CLUSTER:.metadata.labels.'osc\.edu/role'
NAME                 CLUSTER
kubecontroller-dev   <none>
kubeworker01-dev     infrastructure
kubeworker02-dev     ondemand

# TEST
# kubectl get node -o=custom-columns=NAME:.metadata.name,CLUSTER:.metadata.labels.'osc\.edu/role'
NAME                  CLUSTER
kubecontroller-test   <none>
kubeworker01-test     ondemand
kubeworker02-test     ondemand
kubeworker03-test     infrastructure
kubeworker04-test     ondemand
```

**Comment by johrstrom** [comment]
The first comment in this ticket has `role` for both. I'm guessing it should just be `osc.edu/role=ondemand` and `web` was a mistake?

@treydock it should just be 1 label `osc.edu/role=ondemand` right? I'm not sure where I got `web` from.

**Comment by treydock** [comment]
Yep, just need `osc.edu/role=ondemand` , things like R Shiny apps would get `osc.edu/role=web` or something not `ondemand` and not `infra` type deal.  The ondemand role has already been assigned to all production K8 nodes and half the test/dev nodes.

**Comment by treydock** [comment]
To be clear, this label goes in the `node_selector`, not the pod labels.  Looks like bc_osc_jupyter and bc_osc_rstudio_server already have that set.  https://github.com/OSC/bc_osc_jupyter/blob/da24b14416272fa769ee94a01c4b748e7d3d005a/submit.yml.erb#L144-L145
