### ISSUE TITLE
Change the starting directory in terminal to $NOTEBOOK_ROOT

### ISSUE THREAD

**Issue by ZQyou** [OSC/bc_classroom_jupyter#21]
Current starting directory in Jupyter terminal is ondemand working directory. I think it would confuse PI or students who use terminal because it is hard for them to find the notebook working directory `$NOTEBOOK_ROOT`. Can we change the [jupyter command ](https://github.com/OSC/bc_classroom_jupyter/blob/main/template/script.sh.erb#L3) kick-off directory to `$NOTEBOOK_ROOT`?

**Comment by johrstrom** [comment]
> Can we change the [jupyter command ](https://github.com/OSC/bc_classroom_jupyter/blob/main/template/script.sh.erb#L3)kick-off directory to $NOTEBOOK_ROOT?

Sure. I think just a `cd` may work too. But yea, I think that makes sense for the terminal to start where the UI starts.

**Comment by johrstrom** [comment]
This has been released to production. Thanks for the ticket!
